project:
  type: website
  output-dir: docs
execute:
  freeze: auto

website:
  title: "Data Analytics by R and else"
#  favicon: images/favicon.png
  site-url: https://alirezach.github.io
  description: "A passionate Data Analytics and AI enthusiast"
  open-graph:
    locale: en_US
  twitter-card:
    creator: "@alirezach"
  navbar:
#    logo: images/logo-light.png
    logo-alt: "Alireza Chamanzar"
    title: false
    right:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog.qmd
#      - text: About
#        href: about.qmd
      - text: وبلاگ فارسی
        href: https://alirezach.github.io/persian
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/alirezach/alirezach.github.io
          - text: Report a Bug
            url:  https://github.com/alirezach.github.io/issues
      - text: CV
        href: https://alirezach.github.io/cv.pdf
  page-footer:
    border: false
    right: "© [Alireza Chamanzar](https://github.com/alirezach) 2024~"
    left: "Made with ♥ by R and quarto."

format:
  html:
    theme:
      light: sandstone
      dark: sandstone
    css: styles/english.scss
    toc: true
    code-link: true
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
    highlight-style: gruvbox
    df-print: kable

editor: visual